# Generated by Django 2.1.1 on 2018-09-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('xlabel', models.CharField(max_length=30)),
                ('ylabel', models.CharField(max_length=30)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
